### ISSUE TITLE
Restservice Umbauten am HackingDay

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_server#22]
Umbenennung:
Talks -> Events
TalkType -> EventType
Rooms -> Locations

Konferenz-ID in URL mitgeben
rest/conferences/ID/events

Locations: auch names mit de, en

Icon-URLs mitliefern

Bugs fixen:
1. Testdaten mit Community-Aktivitäten liefern Event ohne Speaker:

Testdaten-Fehler: 2015-10-10 08:08:19.855 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[.[jerseyServlet]          : Servlet.service() for servlet [jerseyServlet] in context with path [/testdata] threw exception [java.util.NoSuchElementException: Cannot access first() element from an empty List] with root cause

java.util.NoSuchElementException: Cannot access first() element from an empty List
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.first(DefaultGroovyMethods.java:8929)
        at org.codehaus.groovy.runtime.dgm$222.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
        at org.dukecon.server.business.JavalandDataExtractor$_getSpeakerIdToTalks_closure30.doCall(JavalandDataExtractor.groovy:111)
        at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)

**Comment by sippsack** [comment]
soweit alles durch, bei den Icons müssen wir nochmal schauen, die kommen im Moment in der Form track_1.png, language_de.png usw mit.
